### PR TITLE
Mdns resolver fixes v2

### PR DESCRIPTION
**Pull request by jakogut**
This PR simplifies mDNS resolution, increases the timeout to improve reliability, and memoizes the resolved address to speed up test runs.

### CODE REVIEW

**Review by klutchell — APPROVED** [review]
lgtm

**Comment by klutchell** [comment]
@resin-jenkins retest this please

**Comment by klutchell** [comment]
The generic tests are failing with this PR, the QEMU device never comes online.
```
leviathan-generic-test-client-1  | [2022-05-26T15:25:43.783Z][worker-e2e] DUT powered on
leviathan-generic-test-client-1  | [2022-05-26T15:25:43.783Z][worker-e2e] Creating SSH tunnels to DUT
leviathan-generic-test-client-1  | [2022-05-26T15:25:43.783Z][worker-e2e] Getting ip of dut
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPDISCOVER(brc1uccqyj) 52:54:00:12:34:56 
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPOFFER(brc1uccqyj) 10.10.10.76 52:54:00:12:34:56 
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPDISCOVER(brc1uccqyj) 52:54:00:12:34:56 
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPOFFER(brc1uccqyj) 10.10.10.76 52:54:00:12:34:56 
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPREQUEST(brc1uccqyj) 10.10.10.76 52:54:00:12:34:56 
leviathan-generic-test-worker-1  | dnsmasq-dhcp: DHCPACK(brc1uccqyj) 10.10.10.76 52:54:00:12:34:56 a440455
leviathan-generic-test-client-1  | [2022-05-26T15:55:45.460Z][worker-e2e]     # Subtest: Power Cycle Tests
leviathan-generic-test-client-1  | [2022-05-26T15:55:45.460Z][worker-e2e]         # Subtest: Is the DUT reachable?
leviathan-generic-test-client-1  |             not ok 1 - 500 - "Could not resolve a440455.local"
```

**Comment by jakogut** [comment]
@resin-jenkins retest this please

**Comment by jakogut** [comment]
Closing in favor of: https://github.com/balena-os/leviathan/pull/758

**Pull request closed without merging**
