### PR TITLE
minor: Improve e2e serial test for Leviathan v2

### PR DESCRIPTION
**Pull request by vipulgupta2048**
Todo
- Add a serial pull or an explicit test for each suite to pull the serial for testbot workers. 
- Check if this unblocks GitHub actions progress. 

Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
@vipulgupta2048 I cherry-picked this commit over here but the builds still fail: https://github.com/balena-os/leviathan/pull/777
```
leviathan-client-1  | [2022-06-23T22:55:44.417Z][27718d4-e2e]             # Serial file created at /reports/dut-serial.txt
leviathan-client-1  | [2022-06-23T22:55:44.429Z][27718d4-e2e]             not ok 1 - Size of serial output file from DUT shouldn't be 0
```

**Comment by vipulgupta2048** [comment]
Hey man, @klutchell This is taking longer than expected. I haven't pushed the new changes that I am confident will work. For some reason, I am receiving the serial logs as garbled text in a UTF 16LE encoding and I am trying to find a reason why that happens.

**Comment by klutchell** [comment]
@vipulgupta2048 can you squash some of these commits?

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
