### PR TITLE
add relay based testbot worker (WIP)

### PR DESCRIPTION
**Pull request by rcooke-warwick**
Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
This became the autokit worker which has been added to https://github.com/balena-os/leviathan-worker

**Pull request closed without merging**
