### PR TITLE
add log timestamping

### PR DESCRIPTION
**Pull request by rcooke-warwick**
This adds timestamps to logs recieved by the client. Example output:

```
[2021-06-18T15:36:18.953Z][af82ff1-os] found 0 vulnerabilities
[2021-06-18T15:36:19.004Z][af82ff1-os] Removing artifacts from previous tests...
[2021-06-18T15:36:20.066Z][af82ff1-os] Run queue summary:
[2021-06-18T15:36:20.067Z][af82ff1-os]  Unmanaged BalenaOS release suite
[2021-06-18T15:36:20.067Z][af82ff1-os]   OS corruption tests
[2021-06-18T15:36:20.068Z][af82ff1-os]           resinos.fingerprint file test
[2021-06-18T15:36:20.068Z][af82ff1-os]   OS-release tests
[2021-06-18T15:36:20.068Z][af82ff1-os]           OS-release file check
[2021-06-18T15:36:20.068Z][af82ff1-os]   chrony tests
```

Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
we can probably tidy up the timestamp so it doesn't include the day eg:

 `18 Jun 2021 15:37:44 GMT`

Or maybe there is a better format. Iso gives:

`2021-06-18T15:36:25.643Z`

**Comment by klutchell** [comment]
I think LSO is preferred and more standard.

**Comment by rcooke-warwick** [comment]
The accuracy of these logs are also called into question - as we are timestamping them as they arrive at the client, logs that arrive in batches may not be accurately timestamped. Not sure how misleading they will be, but maybe its worth stamping them before we send them from the testbot, instead of after receiving them

**Review by klutchell — APPROVED** [review]
Nice!

**Review by klutchell — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
