### PR TITLE
enable testing without client uploads

### PR DESCRIPTION
**Pull request by rcooke-warwick**
If you set the env variable `LOCAL=local` then you can stop the core from requesting images and tests to be uploaded from the client

Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
Should we also perhaps explore testing possibilities where we don't have the flash new images or configure networks, again and again, to speed up the local development process. With core now requesting for images we definitely will be using the image and tests we already have. If there is a way to stop flashing the image as well through the Local env, then I think we should check it out. Flashing takes 6 minutes.

**Comment by rcooke-warwick** [comment]
@vipulgupta2048 I like that idea a lot, I think another PR for that would be good. You can actually check for the local env in the test suite to be fair, and then skip steps if you don't want them

**Comment by rcooke-warwick** [comment]
This PR was to be able to use the core + worker with fin QA

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci I self-certify!

**Comment by vipulgupta2048** [comment]
Sounds good to me @rcooke-warwick I think another PR for that would be good. Since flashing and network configuration could be a step that people might want to repeat and not forego.

**Pull request merged**
