### PR TITLE
Run QEMU and testbot e2e tests via github-actions

### PR DESCRIPTION
**Pull request by klutchell**
Depends-on: https://github.com/balena-os/leviathan/pull/786

### CODE REVIEW

**Comment by klutchell** [comment]
This PR is expecting `BALENACLOUD_API_KEY` to be a GH secret with the testbot API key.

**Comment by klutchell** [comment]
Looks like we already have `BALENA_TOKEN` from the `testbot` user as a secret so I will use that.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
Dang it, @klutchell My bad, I rebased using GitHub's button and it seems it does the rebase correctly but not as clean as versionbot. Trying test if your latest commit fixed this or not.

**Comment by klutchell** [comment]
@balena-ci I self-certify!

**Pull request merged**
