### PR TITLE
Add leviathan test helpers package

### PR DESCRIPTION
**Pull request by vipulgupta2048**
- patch: Make global config available to tests
- minor: Add leviathan test helpers package

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
This si ready for review @rcooke-warwick

**Comment by vipulgupta2048** [comment]
Need to fix #522  #504 either after merge or with this PR.

**Comment by klutchell** [comment]
Will the OS jobs be able to set the version of the helpers at runtime? The idea is that the helpers are versioned with the OS code and tests.

**Comment by vipulgupta2048** [comment]
@klutchell so here's my thinking in my head. 
1. The test suites for a particular OS version have test-helpers package specified with a particular version in package.json 
2. The tests run, the dependencies for the tests need to be installed in the environment
3. The exact test-helpers package gets installed. 

In the future, we do ESR testing. 
Old version of tests, will have a old version test-helpers package set, which will be installed on runtime when we are testing the ESR balenaOS. We just need to make sure we increment the helper version in the package.json, and generate the package-lock.json file. We also should be looking out that we set the package versions exactly and not have `^3.0.0`

What do you think, you can check the corresponding meta-balena PR.

**Comment by klutchell** [comment]
> We also should be looking out that we set the package versions exactly and not have ^3.0.0

Package lock files prevent this from being an issue.

> What do you think, you can check the corresponding meta-balena PR.

Which PR is that? We should link it here.

Is it possible to have leviathan use a default version of helpers, in case meta-balena doesn't set a specific version? Just thinking that when we merge/deploy this to leviathan I don't want existing meta-balena branches to break just because they don't know how to specify a helper version.

**Pull request closed without merging**
