### PR TITLE
workers: qemu: enable serial logging

### PR DESCRIPTION
**Pull request by jakogut**
Change-type: patch
Signed-off-by: Joseph Kogut <joseph@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@jakogut if the serial logs for QEMU doesn't give us anything, could we modify the logic to have dmesg inside the serial file? That could be really valuable. What do your think?

**Comment by jakogut** [comment]
@vipulgupta2048 It's not that the serial logs for QEMU don't give us anything, we're getting what the OS is outputting. It looks like the serial console isn't being configured properly on boot, I'm looking at fixing this for the generic images.

**Comment by vipulgupta2048** [comment]
Thanks @jakogut very much indeed. I didn't mean to say the QEMU image didn't give us anything, you are right we are getting what the OS is outputting. If we can't work around this, would the dmesg idea make sense?

**Comment by jakogut** [comment]
@vipulgupta2048 It's tricky, because the console and early boot messages are intentionally disabled for production images, and we removed the distinction between development and production images some time ago. Changing this requires modifying the boot parameters to configure a serial console before boot. I suppose it's possible we could configure a serial console to show the output from dmesg, but we'd then need to reboot to get the output.

For reference, here's the output from the serial log currently:

```
^[[2J^[[01;01H^[[=3h^[[2J^[[01;01H^[[0m^[[35m^[[40m^[[0m^[[37m^[[40mBdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found^M
BdsDxe: loading Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)^M
BdsDxe: starting Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)^M
^[[0m^[[30m^[[47mWelcome to GRUB!
^M
^M^[[0m^[[37m^[[40merror: no such device: ((hd0,gpt1)/EFI/BOOT)/EFI/BOOT/grub.cfg.
^M^[[0m^[[30m^[[40m^[[2J^[[01;01H^[[0m^[[37m^[[40m  Booting `boot'
^M
^M^M^M
balenaOS 2.85.17 dfa4904 ttyS0^M
^M
dfa4904 login: ^[[2J^[[01;01H^[[=3h^[[2J^[[01;01H^[[0m^[[35m^[[40m^[[0m^[[37m^[[40mBdsDxe: failed to load Boot0001 "UEFI QEMU DVD-ROM QM00005 " from PciRoot(0x0)/Pci(0x1F,0x2)/Sata(0x2,0xFFFF,0x0): Not Found^M
BdsDxe: loading Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)^M
BdsDxe: starting Boot0002 "UEFI Misc Device" from PciRoot(0x0)/Pci(0x3,0x0)^M
^[[0m^[[30m^[[47mWelcome to GRUB!
^M
^M^[[0m^[[37m^[[40merror: no such device: ((hd0,gpt1)/EFI/BOOT)/EFI/BOOT/grub.cfg.
^M^[[0m^[[30m^[[40m^[[2J^[[01;01H^[[0m^[[37m^[[40m  Booting `boot'
^M
^M^M^M
balenaOS 2.85.17 dfa4904 ttyS0^M
^M
dfa4904 login: 
```

**Comment by rcooke-warwick** [comment]
@vipulgupta2048 @jakogut , this change can be merged afaict? the change is to allow capture of what the OS is outputting over serial, and that feature works - whether or not the OS is outputting what we want it to output is another matter I think

**Comment by vipulgupta2048** [comment]
@jakogut I agree with Ryan, let's merge this.

**Review by vipulgupta2048 — APPROVED** [review]

**Comment by jakogut** [comment]
@vipulgupta2048 What's the deal with some of the formatting changes in the [commit](https://github.com/balena-os/leviathan/commit/837c0f4905700029dc458730808dd598d85d6e83) that conflicts with this?  Many of them are good formatting fixes, but specifically, the reformatting of the arguments to QEMU is, in my opinion, _less_ readable.

For example:

```diff
                let baseArgs = [
                        '-nographic',
-                       '-m', this.qemuOptions.memory,
-                       '-smp', this.qemuOptions.cpus,
-                       '-drive', 'format=raw,file=/data/os.img,if=virtio',
+                       '-m',
+                       this.qemuOptions.memory,
+                       '-smp',
+                       this.qemuOptions.cpus,
+                       '-drive',
+                       'format=raw,file=/data/os.img,if=virtio',
                ];
```

And this:

```diff
                //
                // Disable S3 support to work around a Debian bug
                // https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973783
-               let firmwareArgs: { [arch: string]: Array<string> } = {
-                       'x86_64': [
-                               '-global', 'driver=cfi.pflash01,property=secure,value=on',
-                               '-global', 'ICH9-LPC.disable_s3=1',
-                               '-drive', 'if=pflash,format=raw,unit=0,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on',
-                               '-drive', 'if=pflash,format=raw,unit=1,file=/usr/share/OVMF/OVMF_VARS.fd',
+               const firmwareArgs: { [arch: string]: string[] } = {
+                       x86_64: [
+                               '-global',
+                               'driver=cfi.pflash01,property=secure,value=on',
+                               '-global',
+                               'ICH9-LPC.disable_s3=1',
+                               '-drive',
+                               'if=pflash,format=raw,unit=0,file=/usr/share/OVMF/OVMF_CODE.fd,readonly=on',
+                               '-drive',
+                               'if=pflash,format=raw,unit=1,file=/usr/share/OVMF/OVMF_VARS.fd',
                        ],
```

Was this the product of an automated reformatter? Like I said, many of these reformatting fixes were good, but some were not, and they probably shouldn't have been committed all together without closer review. Specifically, the array reformatting lacked the context of understanding that the argument value followed the argument, and was on the same line for readability.

There _were_ a lot of inconsistencies in the formatting, so I'm not opposed to fixing those. However, I think in these two instances, the code was more readable before.

**Pull request merged**
