### PR TITLE
Adds package for util to e2e suite.js

### PR DESCRIPTION
**Pull request by Bucknalla**
Change-type: patch
Signed-off-by: Alex Bucknall <alex.bucknall@gmail.com>

### CODE REVIEW

**Review by vipulgupta2048 — APPROVED** [review]
Nitpick: Are the formatting changes something you explicitly made or did they creep in from your editor? If it is the latter, please run `npm run lint:fix` instead. Trying to standardise formatting for the project.
Thanks for the PR 🎉

**Comment by Bucknalla** [comment]
Sure

**Comment by rcooke-warwick** [comment]
this looks fine to me. tbh I'm suprised it ever ran if there was a package missing?

**Comment by Bucknalla** [comment]
@balena-ci rebase

**Comment by Bucknalla** [comment]
@vipulgupta2048 I ran it through the linter and prettifer and it introduced even more changes 🤷

**Pull request merged**
