### PR TITLE
reduce ssh retries

### PR DESCRIPTION
**Pull request by rcooke-warwick**
reduce from 300 retries to 30 

Could be more of an aggressive reduction, but lets see how this affects things first

resolves: https://github.com/balena-os/leviathan/issues/793 https://github.com/balena-os/leviathan/issues/787

Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
@balena-ci retest

**Comment by klutchell** [comment]
@rcooke-warwick the failed test is from Github Actions, and `@balena-ci` won't help retry them. Click on the action details and there is a retry button in the top right.

This is the timeout bug: https://github.com/balena-os/leviathan/issues/792

**Comment by klutchell** [comment]
> @vipulgupta2048 @klutchell iirc we've introduced problems in the past by reducing the number of retries here?

I don't recall a specific issue with this change, do you remember what broke?

**Comment by rcooke-warwick** [comment]
I think I must have been remembering this: https://github.com/balena-os/leviathan/pull/542

But those retries are not related to this particular change, so shouldn't be a problem

**Review by klutchell — APPROVED** [review]

**Comment by klutchell** [comment]
@rcooke-warwick testing generic-aarch64 locally this does not seem to be enough retries to pass the HUP suite.
```
leviathan-client-1  | [2022-07-11T22:57:40.292Z][worker-hup]         # Breaking init to trigger rollback-altboot...
leviathan-client-1  | [2022-07-11T22:57:41.071Z][worker-hup] Rebooting the DUT
leviathan-client-1  | [2022-07-11T22:57:45.197Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:45.198Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:45.726Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:45.726Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:46.215Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:46.215Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:47.232Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:47.232Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:48.246Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:48.246Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:49.227Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:49.227Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:50.244Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:50.244Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:51.249Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:51.250Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:52.217Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:52.218Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:53.254Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:53.254Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:54.216Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:54.216Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:55.250Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:55.250Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:56.215Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:56.215Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:57.218Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:57.218Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:58.226Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:58.226Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:57:59.215Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:57:59.215Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:00.367Z][worker-hup] read ECONNRESET
leviathan-client-1  | [2022-07-11T22:58:00.367Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:01.207Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:01.207Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:02.205Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:02.205Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:23.204Z][worker-hup] Timed out while waiting for handshake
leviathan-client-1  | [2022-07-11T22:58:23.205Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:33.368Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:33.368Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:36.440Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:36.440Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:39.512Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:39.512Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:42.584Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:42.585Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:45.656Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:45.656Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:48.728Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:48.728Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:51.800Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:51.800Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:54.872Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:54.872Z][worker-hup] executeCommandInHostOS "[[ ! -f /tmp/reboot-check ]] && echo pass" failed, will retry...
leviathan-client-1  | [2022-07-11T22:58:54.883Z][worker-hup]         not ok 1 - Error: connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]           ---
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]           stack: |
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]             retry.max_tries (lib/common/worker.js:324:12)
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]           at:
leviathan-client-1  |             line: 324
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]             column: 12
leviathan-client-1  |             file: lib/common/worker.js
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]             function: retry.max_tries
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]           test: Rollback altboot (broken init) test
leviathan-client-1  |           source: |
leviathan-client-1  | [2022-07-11T22:58:54.884Z][worker-hup]                                                    console.log(`executeCommandInHostOS "${command}" failed, will retry...`);
leviathan-client-1  |                                                   throw new Error(err);
leviathan-client-1  | [2022-07-11T22:58:54.885Z][worker-hup]             -----------^
leviathan-client-1  |                                           }
leviathan-client-1  | [2022-07-11T22:58:54.885Z][worker-hup]           ...
leviathan-client-1  | [2022-07-11T22:58:54.895Z][worker-hup] 
leviathan-client-1  | [2022-07-11T22:58:54.895Z][worker-hup]         Bail out! Error: connect EHOSTUNREACH 10.10.10.76:22222
leviathan-client-1  | [2022-07-11T22:58:54.900Z][worker-hup] Bail out! Error: connect EHOSTUNREACH 10.10.10.76:22222
```
For whatever reason, if this inner hardcoded retry limit is hit and throws, none of the outer retries will catch it or try again.

**Comment by klutchell** [comment]
I think we need to get rid of the inner hardcoded retry in worker.js, and turn up the defaults in sdk.js to compensate. That way the retries are fully exposed to the test suite.

**Comment by rcooke-warwick** [comment]
It's should still give around 3 to 4 minutes worth of retries, when running locally is this on an x86 host so it's slower?

**Comment by rcooke-warwick** [comment]
@klutchell we could, at the moment it's just making things that would fail anyway surface quicker - if it's stopping tests from passing then we should probably revert it.

**Comment by klutchell** [comment]
> @klutchell we could, at the moment it's just making things that would fail anyway surface quicker - if it's stopping tests from passing then we should probably revert it.

I've seen it locally, and it looks like [the PR to bump leviathan](https://github.com/balena-os/meta-balena/pull/2715) is failing in the same place.
https://jenkins.product-os.io/job/leviathan-v2-template/2727/console
```
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:00.750Z][worker-hup]             # Reducing timeout for rollback-health...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:02.939Z][worker-hup] Rebooting the DUT
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:07.690Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:07.691Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:08.181Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:08.181Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:08.721Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:08.721Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:09.717Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:09.717Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:10.716Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:10.716Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:11.716Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:11.716Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:12.716Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:12.717Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:13.718Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:13.718Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:14.720Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:14.720Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:15.720Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:15.723Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:16.719Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:16.719Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:17.719Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:17.719Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:18.718Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:18.718Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:19.732Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:19.732Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:20.723Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:20.724Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:21.721Z][worker-hup] read ECONNRESET
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:21.722Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:22.701Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:22.702Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:23.702Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:23.702Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:24.700Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:24.701Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:25.700Z][worker-hup] connect ECONNREFUSED 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:25.700Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:46.701Z][worker-hup] Timed out while waiting for handshake
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:35:46.701Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:06.702Z][worker-hup] Timed out while waiting for handshake
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:06.703Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:16.908Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:16.909Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:19.981Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:19.981Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:23.052Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:23.053Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:26.125Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:26.126Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:29.197Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:29.197Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.269Z][worker-hup] connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.269Z][worker-hup] Error while performing SSH command "[[ ! -f /tmp/reboot-check ]] && echo pass", will retry...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.286Z][worker-hup]             not ok 1 - Error: connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.286Z][worker-hup]               ---
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.287Z][worker-hup]               stack: |
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.287Z][worker-hup]                 retry.max_tries (lib/common/worker.js:324:12)
jenkins-leviathan-v2-template-2727-client-1  |               at:
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.287Z][worker-hup]                 line: 324
jenkins-leviathan-v2-template-2727-client-1  |                 column: 12
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.289Z][worker-hup]                 file: lib/common/worker.js
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.289Z][worker-hup]                 function: retry.max_tries
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.289Z][worker-hup]               test: HUP from previous release
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.289Z][worker-hup]               source: >
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.290Z][worker-hup]                 					console.log(`Error while performing SSH command "${command}", will retry...`);
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.290Z][worker-hup]                 					throw new Error(err);
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.290Z][worker-hup]                 -----------^
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.290Z][worker-hup]                 				}
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.290Z][worker-hup]               ...
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.303Z][worker-hup] 
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.304Z][worker-hup]             Bail out! Error: connect EHOSTUNREACH 10.10.10.76:22222
jenkins-leviathan-v2-template-2727-client-1  | [2022-07-11T20:36:32.312Z][worker-hup] Bail out! Error: connect EHOSTUNREACH 10.10.10.76:22222
```
[consoleText.txt](https://github.com/balena-os/leviathan/files/9095958/consoleText.txt)

**Pull request merged**
