### PR TITLE
bump dbus package

### PR DESCRIPTION
**Pull request by rcooke-warwick**
Change-type: patch
Signed-off-by: Ryan Cooke <ryan@balena.io>

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
based on this https://github.com/dbusjs/node-dbus-next/issues/39, updating this package may help with the dbus issue multiple devices are showing: https://github.com/balena-io/testbot/issues/49

**Comment by vipulgupta2048** [comment]
Looking good @rcooke-warwick not sure how you weren't prompted with that commit error I was seeing maybe the linters judge you change if you make it to source code not `package.json`. I will merge it tomorrow.

**Comment by vipulgupta2048** [comment]
@rcooke-warwick I just realised you also need to npm install with this to update the package-lock.json --> before we merge this.

**Comment by vipulgupta2048** [comment]
Closing in favor of #368

**Pull request closed without merging**
