### PR TITLE
Enable aarch64 QEMU workers

### PR DESCRIPTION
**Pull request by klutchell**
Change-type: patch
Signed-off-by: Kyle Harding <kyle@balena.io>
See: https://github.com/balena-os/meta-balena/issues/2554

### CODE REVIEW

**Comment by rcooke-warwick** [comment]
just for clarity - the core container has problems running on arm64 hosts too - we have a PR here to fix that here: https://github.com/balena-os/leviathan/pull/711

that will also need to be merged to enable the full stack to run on arm64 hosts

**Comment by rcooke-warwick** [comment]
as per [1d824e2](https://github.com/balena-os/leviathan/pull/707/commits/1d824e2c245487f3d52bb4204437f6af71427d12)

this builds on arm64

**Comment by klutchell** [comment]
I'll give this a retest today, but it looks good from here

**Comment by klutchell** [comment]
@balena-ci I self-certify!

**Pull request merged**
