### PR TITLE
Add RevPi Core 3

### PR DESCRIPTION
**Pull request by acostach**
Change-type: patch
Signed-off-by: Alexandru Costache <alexandru@balena.io>

### CODE REVIEW

**Comment by acostach** [comment]
This should be ready for review now @rcooke-warwick @vipulgupta2048

**Comment by acostach** [comment]
@rcooke-warwick @vipulgupta2048 ok to deploy / merge this?

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by acostach** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
lgtm

**Review by rcooke-warwick — APPROVED** [review]

**Pull request merged**
