### PR TITLE
Document proper worker config for QEMU workers

### PR DESCRIPTION
**Pull request by lmbarros**
Main change here is updating the docs on how to set `workers` in order to use QEMU workers. From my experience and from a quick look at the source, using `http://worker` (instead of `http://localhost`) is the way to go.

Also fixes a few typos.

### CODE REVIEW

**Comment by lmbarros** [comment]
@balena-ci retest

**Comment by lmbarros** [comment]
@resin-jenkins retest this please

**Comment by vipulgupta2048** [comment]
Hey @lmbarros How about splitting the docs fix into a different PR for us to review later? We already have an issue on that: https://github.com/balena-os/leviathan/issues/780

Regarding the issue itself, how about making the workaround fix for the taskqueue, generate the docs and then revert the change you made. 

And, now regarding the PR

**Comment by jakogut** [comment]
Vipul's suggestions seem good to me, if these were separate PR's, I'd approve it.

**Comment by lmbarros** [comment]
@vipulgupta2048 , @jakogut Thanks for the comments! This PR was quite messy, indeed (I kept adding just one more commit to it...)

Now this PR contains only the fixes to the docs comments, and the (improved) fix to the `npm run build` moved over here: https://github.com/balena-os/leviathan/pull/813.

**Review by vipulgupta2048 — APPROVED** [review]
Ship it
giphy

**Pull request merged**
