### PR TITLE
patch: Add docs/ to .dockerignore

### PR DESCRIPTION
**Pull request by vipulgupta2048**
- [ ] Update the CLI version if this PR is merged and locally tested https://github.com/balena-io/balena-cli/pull/2300

Update: 
Will update the CLI version in the core, after the armv7 blockers have been solved. 
Context: https://www.flowdock.com/app/rulemotion/p-testbot/threads/fsdypCCB26VorkBxBuY_MTZMqAp

### CODE REVIEW

**Comment by klutchell** [comment]
Looks good to me, but I'm not sure how the CLI PR is related to this PR?

**Comment by vipulgupta2048** [comment]
@klutchell oh this was such a small change so I was thinking IF the CLI fix would have worked out. I would have use this PR to do both dockerignore + CLI update

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci I self-certify!

**Pull request merged**
