### PR TITLE
Restore QEMU worker

### PR DESCRIPTION
**Pull request by jakogut**

### CODE REVIEW

**Review by vipulgupta2048 — COMMENTED** [review]
Good work, @jakogut looking forward to this. Do remove the libvrt dependencies from the Worker Dockerfile as well.

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by jakogut** [comment]
@rcooke-warwick You should be able to get output from QEMU to see if it's not booting for some reason by adding `{stdio: 'inherit'}` after `args` in `worker/lib/worker/qemu.ts:161`.

**Comment by rcooke-warwick** [comment]
hey @jakogut , thank you, I've done as you suggested, and it seems like its getting stuck at the UEFI boot screen?
```
UEFI Interactive Shell v2.2
worker_1  | EDK II
worker_1  | UEFI v2.70 (EDK II, 0x00010000)
worker_1  | Mapping table
worker_1  |       FS0: Alias(s):HD2b:;BLK4:
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(1,MBR,0x00000000,0x2000,0x14000)
worker_1  |      BLK2: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x1,0x1)/Ata(0x0)
worker_1  |      BLK3: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)
worker_1  |      BLK5: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(2,MBR,0x00000000,0x16000,0x9C000)
worker_1  |      BLK6: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(3,MBR,0x00000000,0xB2000,0x9C000)
worker_1  |      BLK7: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(4,MBR,0x00000000,0x14E000,0x210000)
worker_1  |      BLK8: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(4,MBR,0x00000000,0x14E000,0x210000)/HD(1,MBR,0x00000000,0x150000,0xA000)
worker_1  |      BLK9: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x4,0x0)/HD(4,MBR,0x00000000,0x14E000,0x210000)/HD(2,MBR,0x00000000,0x15C000,0x202000)
worker_1  |      BLK0: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x1,0x0)/Floppy(0x0)
worker_1  |      BLK1: Alias(s):
worker_1  |           PciRoot(0x0)/Pci(0x1,0x0)/Floppy(0x1)
Press ESC in 1 seconds to skip startup.nsh or any other key to continue.
```

**Comment by rcooke-warwick** [comment]
@jakogut if you can rebase this against master to remove the conflict this can be merged. I then have a followup PR to make with some additional changes made over the last day

**Comment by rcooke-warwick** [comment]
@balena-ci retest

**Review by rcooke-warwick — APPROVED** [review]

**Pull request merged**
