### PR TITLE
Add archiveLogs helpers and update Archiver implementation 

### PR DESCRIPTION
**Pull request by vipulgupta2048**
The changes are as follows:
1. Create new archiveLogs helper
2. Create new implementation of the Archiver module
3. Add documentation for Archiver module

Change-type: patch
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipul@balena.io>

### CODE REVIEW

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Comment by rcooke-warwick** [comment]
@balena-ci rebase

**Comment by vipulgupta2048** [comment]
@balena-ci rebase

**Pull request merged**
